name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
   # extract branch name
    - name: Extract branch name
      if: github.event_name != 'pull_request'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      id: extract_branch
      
    # extract branch name on pull request
    - name: Extract branch name on pull request
      if: github.event_name == 'pull_request'
      run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV
      
    # print branch name
    - name: Get branch name
      run: echo "The branch name is ${{ env.BRANCH_NAME }}"

      
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
        
    - name: Install dependencies
      run: dotnet restore Dynamic.OData.sln
    
    - name: Build
      run: dotnet build Dynamic.OData.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test Dynamic.OData.sln --no-build --configuration Release --verbosity m
          
